//! Embeds the Windows application icon into the `gemray-worker` binary.
//!
//! `assets/icon.ico` is generated by `scripts/make-icons.py` (emerald, to tell this
//! binary apart from the cyan viewer at a glance in a taskbar or an output directory
//! full of PGO build variants). Windows also uses an executable's first icon resource
//! for its console window, so this is what a `gemray-worker` terminal shows too.
//!
//! # This crate deliberately keeps its console
//!
//! Unlike `diagram-gui`, there is no `windows_subsystem = "windows"` anywhere in this
//! crate. `gemray-worker` is a command-line tool: `render` prints progress, `serve`
//! streams `tracing` output for the life of the server, and `cert` prints the
//! fingerprints an operator has to read. Marking it as a Windows-subsystem binary would
//! detach stdout from the parent console, so running `gemray-worker serve` from a
//! terminal would print absolutely nothing. An icon is cosmetic; the console is the
//! interface.
//!
//! # Failure is a warning, not an error
//!
//! Embedding needs a resource compiler -- `rc.exe` from the Windows SDK for an `msvc`
//! target, `windres` for `gnu`. Neither is guaranteed present, particularly when
//! cross-compiling (see `scripts/pgo-bolt-build.sh`, which builds
//! `x86_64-pc-windows-gnu` from a Linux host). A missing icon must never be the reason
//! a build fails, so this reports and continues.

fn main() {
    #[cfg(windows)]
    embed_icon();
}

#[cfg(windows)]
fn embed_icon() {
    println!("cargo:rerun-if-changed=assets/icon.ico");
    let mut res = winresource::WindowsResource::new();
    res.set_icon("assets/icon.ico");
    if let Err(e) = res.compile() {
        println!(
            "cargo:warning=could not embed the application icon ({e}); the binary will build without one"
        );
    }
}
