//! Compiles the Slint UI, and on Windows embeds the application icon.
//!
//! `assets/icon.ico` is generated by `scripts/make-icons.py` (cyan, against
//! `gemray-worker`'s emerald). Embedding it as a resource covers both places Windows
//! shows an icon: Explorer's view of the `.exe`, and the window's own titlebar and
//! taskbar button -- a Win32 window with no icon of its own falls back to the
//! executable's first icon resource, so no per-window `set_icon` call is needed and
//! there is no runtime dependency on the file being installed next to the binary.
//!
//! # Failure is a warning, not an error
//!
//! Embedding needs a resource compiler -- `rc.exe` from the Windows SDK for an `msvc`
//! target, `windres` for `gnu`. Neither is guaranteed present, particularly when
//! cross-compiling (see `scripts/pgo-bolt-build.sh`, which builds
//! `x86_64-pc-windows-gnu` from a Linux host). A missing icon must never be the reason
//! a build fails, so this reports and continues. The Slint compile above is a different
//! matter: without it there is no UI at all, so that one still panics.

fn main() {
    slint_build::compile("ui/app.slint").unwrap();

    #[cfg(windows)]
    embed_icon();
}

#[cfg(windows)]
fn embed_icon() {
    println!("cargo:rerun-if-changed=assets/icon.ico");
    let mut res = winresource::WindowsResource::new();
    res.set_icon("assets/icon.ico");
    if let Err(e) = res.compile() {
        println!(
            "cargo:warning=could not embed the application icon ({e}); the binary will build without one"
        );
    }
}
